### ISSUE TITLE
TypeError: motionMediaQuery_1.addEventListener is not a function [BUG]

### ISSUE THREAD

**Issue by nullhook** [framer/motion#805]
After upgrading from 2.7.8 to 2.9 in my nextjs project... I get the following error, only on Safari.

```
TypeError: motionMediaQuery_1.addEventListener is not a function. (In 'motionMediaQuery_1.addEventListener("change", setReducedMotionPreferences)'
```

specs:
safari: 13.0
framer-motion: 2.9
nextjs: 9.5.4

**Comment by nullhook** [comment]
Looks like Safari handles listeners for matchMedia differently?

Adding the below code worked, locally.

```js
try {
  motionMediaQuery_1.addEventListener("change", setReducedMotionPreferences);
  } catch (e) {
    try {
      motionMediaQuery_1.addListener(setReducedMotionPreferences);
    } catch (e1) {
      console.error(e1);
    }
 }
```

**Comment by nullhook** [comment]
Downgraded to 2.7.6 to fix this issue

**Comment by mattgperry** [comment]
Thanks for the report! I'll be releasing 2.9.1 with a fix shortly

**Comment by lcnogueira** [comment]
Thanks, @nullhook and @mattgperry . I was facing exactly the same issue 🤝 😍
