### ISSUE TITLE
Error in Framer Motion 7.1.0 (works in 6.3.3)

### ISSUE THREAD

**Issue by steven-tey** [framer/motion#1662]
I'm using `Reorder` from `framer-motion`, but when I recently upgraded to 7.1.0, it threw an error:

```
Attempted import error: 'useId' is not exported from 'react' (imported as 'useId')
```

It was working 6.3.3 so I downgraded back to it.

For context I'm using Next.js 12.2.

**Comment by okonomi** [comment]
I was getting the same error.

After checking, it appears that this error is an attempt to call `useId`, which was added in React 18, but it cannot be found.

https://reactjs.org/blog/2022/03/29/react-v18.html#useid

I was using React 17 in my project and this is exactly what happened.
I downgraded to framer-motion v6.5.1 as a response and it solved the problem.

So, you may want to check the React version.

**Comment by mattgperry** [comment]
7.0 was a move to React 18 as a minimum https://www.framer.com/docs/guide-upgrade/#70

**Comment by eshaffer321** [comment]
For nextjs user you need to upgrade to react 18 https://nextjs.org/docs/advanced-features/react-18/overview

**Comment by Doctor-DC** [comment]
> 7.0 was a move to React 18 as a minimum https://www.framer.com/docs/guide-upgrade/#70


framer-motion@6
TypeError: mixerFactory is not a function
